---
functional:
  - Пользователь должен иметь возможность зарегистрироваться на сайте 
  - Пользователь должен иметь возможность создать игру и принять в ней участие
  - В игре должна участвовать вторая сторона (реальный человек, бот)
  - В игре должен присутствовать редактор для написания кода
  - В игре должен присутствовать вывод тестов
  - Игрок должен видеть код своего соперника в режиме онлайн
  - Каждый игрок должен иметь кнопку "check" для проверки своего решения
  - Когда один из игроков находит верное решение, обоим игрокам должно высвечиваться модальное окно, где написано, кто является победителем игры
  - После окончания игры и выхода игроков игра должна считаться завершенной и удаляться из памяти 
non-functional:
  - Проект должен быть разработан с учетом удобства использования и быть оптимизирован для скорости работы
  - Проект должен быть безопасным и должен защищать данные пользователя
  - Проект должен иметь мобильную версию
  - Проект должен выдерживать большое количество трафика и пользователей
  - Проект должен быть доступен на различных устройствах
  - В проекте должна быть возможность выбора языка
implicit:
  - Если один из игроков вылетел из игры, второй может продолжать играть. Первый в любой момент игры должен иметь возможность переподключиться к ней и продолжить играть
  - В проекте должен присутствовать рейтинг игроков 
  - В режиме игры должна присутствовать возможность "Сдаться" и соответствующая кнопка для нее
  - Возможность выбора сложности игры
  - Завершенная игра должна быть доступна для записи и просмотра
